name: Promote to production

on:
  push:
    branches: [ "master" ]

jobs:
  promote-to-production:
    name: Promote to production
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        uses: indiesdev/curl@v1.1
        with:
          url: https://api.heroku.com/pipeline-promotions
          method: "POST"
          accept: 201
          headers: '{ "Accept": "application/vnd.heroku+json; version=3", "Content-Type": "application/json" }'
          body: '{"pipeline":{"id":"80aca7a6-ebbe-4e24-978b-1201037b4ae8"},"source":{"app":{"id":"f2424464-c135-40b0-87b2-6d15b312afe5"}},"targets":[{"app":{"id":"9dc10619-23de-4efa-b246-10534d0407da"}}]}'
          timeout: 5000
          bearer-token: ${{secrets.HEROKU_API_KEY}}